// SignIn Steps.
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';

export const AUTH_ACTIONS = {
  LOGIN_REQUEST: LOGIN_REQUEST,
  LOGIN_SUCCESS: LOGIN_SUCCESS,
  LOGIN_FAILURE: LOGIN_FAILURE,
  LOGOUT_REQUEST: LOGOUT_REQUEST,
  LOGOUT_SUCCESS: LOGOUT_SUCCESS,
  LOGOUT_FAILURE: LOGOUT_FAILURE
};

/////////
//Basket
////////

export const BASKET_ADD = 'BASKET_ADD';

export const BASKET_ACTIONS = {
  ADD: BASKET_ADD
};