////////////////
// User Actions
////////////////
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const TOKEN_AUTH_REQUEST = 'TOKEN_AUTH_REQUEST';
export const TOKEN_AUTH_SUCCESS = 'TOKEN_AUTH_SUCCESS';
export const TOKEN_AUTH_FAILURE = 'TOKEN_AUTH_FAILURE';
export const TOKEN_REFRESH_REQUEST = 'TOKEN_REFRESH_REQUEST';
export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS';
export const TOKEN_REFRESH_FAILURE = 'TOKEN_REFRESH_FAILURE';
export const TOKEN_REVOKE_REQUEST = 'TOKEN_REVOKE_REQUEST';
export const TOKEN_REVOKE_SUCCESS = 'TOKEN_REVOKE_SUCCESS';
export const TOKEN_REVOKE_FAILURE = 'TOKEN_REVOKE_FAILURE';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_FAILURE = 'USER_FAILURE';

export const USER_ACTION = {
  LOGIN_REQUEST,
  LOGIN_SUCCESS,
  LOGIN_FAILURE,
  LOGOUT_REQUEST,
  LOGOUT_SUCCESS,
  LOGOUT_FAILURE,
  TOKEN_AUTH_REQUEST,
  TOKEN_AUTH_SUCCESS,
  TOKEN_AUTH_FAILURE,
  TOKEN_REFRESH_REQUEST,
  TOKEN_REFRESH_SUCCESS,
  TOKEN_REFRESH_FAILURE,
  TOKEN_REVOKE_REQUEST,
  TOKEN_REVOKE_SUCCESS,
  TOKEN_REVOKE_FAILURE,
  USER_REQUEST,
  USER_SUCCESS,
  USER_FAILURE
};

/////////
//Basket
////////

export const BASKET_ADD = 'BASKET_ADD';

export const BASKET_ACTIONS = {
  ADD: BASKET_ADD
};